# Generated by Django 4.2.2 on 2024-04-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('intercept_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('prompt_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('response_url', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_to_image.apirequest')),
            ],
        ),
    ]
