# Generated by Django 4.2.2 on 2024-04-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='content',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
