# Generated by Django 4.2.2 on 2024-04-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0003_alter_prompt_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('response_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intercepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='request',
        ),
        migrations.DeleteModel(
            name='ApiRequest',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.AddField(
            model_name='prompts',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text_to_image.requests'),
        ),
    ]
