# Generated by Django 4.2.2 on 2024-04-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0004_prompts_requests_remove_prompt_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompts',
            old_name='request_id',
            new_name='request',
        ),
    ]
